### PR TITLE
Allow better support for conversations in groups

### PR DESCRIPTION
**Pull request by mkotb**
- A user filter was added to only have a select set of user(s) be part of the conversation in a group
- A `repliesOnly` field was added to have it so only messages which replied to a message sent by a bot will invoke prompts
- Allow multiple conversations to be active at the same time in the internals

### CODE REVIEW

**Comment by wrxck** [comment]
@mkotb I love this bot

**Comment by zackpollard** [comment]
@mkotb This looks good to me, i'll have it merged into development shortly for testing

**Comment by mkotb** [comment]
any update

**Comment by stuntguy3000** [comment]
@mkotb no

**Comment by zackpollard** [comment]
@mkotb Right now we are modularising the conversation and keyboard APIs so once that's done you will need to modify the PR to make it mergable and then it will get accepted

**Comment by stuntguy3000** [comment]
Cheers @zackpollard I'll get right on that

**Comment by DarkSeraphim** [comment]
@zackpollard it might merge automatically if you merge this one first

**Comment by mkotb** [comment]
Additions for conversations are as such:
- End callbacks, which is executed when the conversation has ended. Allows for messages to be sent at the end of a conversation
- End predicates, if returns true, the conversation will be ended.
- Timeouts for conversations, if the conversation has not ended within a specified time, the conversation will end and if provided, a message unique to timeouts will be sent.

**Pull request merged**
