### PR TITLE
Feature/supporting channel posts

### PR DESCRIPTION
**Pull request by mkhoudary**
I have added support for the Channel Posts, whenever I receive a post from a channel I get a NullPointerException, so I extended your last version to support channels and to distinguish between public and private channels since the first one uses username while the other uses chat id.

### CODE REVIEW

**Comment by zackpollard** [comment]
Thank you for this PR, i'm going to be implementing this in the next few days hopefully. Just working on finishing up the game update that I fell behind on, then this stuff should be implemented

**Comment by mkhoudary** [comment]
Great!, I will be working on my fork until you finish, please keep me updated

**Comment by zackpollard** [comment]
Hey there, i've made the changes in the latest develop that adds support for this. I didn't use your PR for a couple of reasons that I will details below. Firstly, there were a lot of changes, including modularisation, that would make this a pain to merge in. Also, my implimentation doesn't work in the exact same way as yours, for example, there are no new events, the new posts just call the original MessageReceivedEvent (and the specific derivatives of that). Having seperate events would break the current design, as we don't do that for any other specific type of chat. I also haven't created two seperate Channel objects for the same reason, we don't have Private and Public types for any other chat types. These new updates should be merged into master in the next few days along with the new modularisation code and the game code. Thanks for your PR :)

Also, as a side note, if you want to come join us on telegram, we have a bunch of people who use this API in a chat https://telegram.me/javaapi

**Comment by mkhoudary** [comment]
I am glad changes were done.. :-) I will be looking for the next release.. Thank you for the awesome work..

**Pull request closed without merging**
