### PR TITLE
Add Inline Menu API

### PR DESCRIPTION
**Pull request by mkotb**
This addition adds an Inline Menu API for developers to use.

Example code:

And how it is used is demoed here: https://youtu.be/2PEjqYiNL0M

### CODE REVIEW

**Comment by nickrobson** [comment]
Is there a way to set the message text inside one of the callbacks? (since I have to assume that the button#setText would set the button's text)

**Comment by mkotb** [comment]
Yep, refer to the newly added setMessageText method.

**Comment by nickrobson** [comment]
:+1:

**Comment by mkotb** [comment]
Refactor made to improve logic flow, to set the message text you would do the following with the button:

``` java
button.getMenu().setMessageText(SendableTextMessage.markup("*Updated Text*"));
```

**Comment by zackpollard** [comment]
Could you please resolve the merge conflicts that exist with the current branch (probably due to the addition of documentation) and document this API as everything from now will be documented

**Comment by mkotb** [comment]
Merged, and added documentation @zackpollard

**Comment by alebabai** [comment]
@mkotb, Hi.
I would like to share some thoughts about menu public API. First of all thank you for your work, a lot of things done perfectly.
But in my opinion menu public API doesn't seems like well designed. There a lot things are not obvious and not useful, I think.

Some sub builders have a lot builds methods from super classes (e.g. SubInlineMenuButtonBuilder has build(), buildMenu(), buildRow() methods).
Also methods like newRow(), subMenu() and etc should have main InlineMenuBuilder return type and would be better to add rows and submenus as method parameters so you can see the nesting as it is done in ReplyKeyboardMarkup or InlineKeyboardMarkup builders.

Also some you methods require builders instead of domain objects, e.g. method message() InlineMenuBuilder require SendableTextMessageBuilder instead of SendableTextMessage.
Maybe someone noticed something else.

This is not a complaint, or something else, just suggestions for improvement.

Regards, 
Alexander.

**Comment by mkotb** [comment]
@alebabai 

Hey! Thanks for the comments, they're always greatly appreciated. There were a few iterations of redesigning when it came to the Menu API and they were discussed between mostly Mark and me in the group chat. Let me address some of your concerns:

> Some sub builders have a lot builds methods from super classes ... has build(), buildMenu(), buildRow() methods

Yes! This was completely intentional, actually. Originally this was the case and the API was quite verbose as compared to how it is now. This was added later on as per Mark's suggestion. Take a look at the original design if we didn't have those additional build methods [here](https://gist.github.com/mkotb/61a4256573a56ab207ed257c2564eb9b/29e6aff35b2bfc0ceaa70e320644af67bfd6ff53)

> Also methods like newRow(), subMenu() and etc should have main InlineMenuBuilder return type and would be better to add rows and submenus as method parameters

Why? I feel like it's more work on the developer and more icky code. I liked using a consistent builder flow throughout the process. If there is an issue with the lack of documentation, I'd be happy to add it.

> Also some you methods require builders instead of domain objects, e.g. method message() InlineMenuBuilder require SendableTextMessageBuilder instead of SendableTextMessage.

Yes, I do, this is to be able to utilize the static methods I added such as `markdown(String)`, `html(String)`, and `plain(String)` for ease of use.

I'm interested in hearing back from you! Sometimes it may seem like a lack of thought which brought upon these design decisions, however, if you look through the history and just a bit closer, it's not that at all.

If you're interested, we can always further discuss these issues either in the [API Group Chat](https://telegram.me/javaapi), or PM me on Telegram at @MazenK

Best Regards,
Mazen Kotb.

**Comment by alebabai** [comment]
@mkotb Thanks, I understand your points for this questions.

> Yes, I do, this is to be able to utilize the static methods I added such as markdown(String), html(String), and plain(String) for ease of use.

I mean that builders aren't domain objects, they are simply as utils elements and should not be visible in the top level of API. Clients can  pass complete SendableTextMessage as method params. Maybe it's less convenient, but more clearly.

> Sometimes it may seem like a lack of thought which brought upon these design decisions, however, if you look through the history and just a bit closer, it's not that at all.

Quite so, my mistake)

**Pull request merged**
