### PR TITLE
Allow sending of InputStreams via InputFile

### PR DESCRIPTION
**Pull request by nickrobson**
This is a non-API-breaking change so can be committed for a 1.x.0 versioning cycle!

I've tested it and it works.

Telegram bot: @graphibot, may or may not be online, idk.
I can bring it online when I am if proof is needed!

### CODE REVIEW

**Comment by bo0tzz** [comment]
@nickrobson .

**Comment by devmattrick** [comment]
@bo0tzz oh god I love memes

**Comment by bo0tzz** [comment]
@bo0tzz Mfwwwww

**Comment by matthewhesketh** [comment]
@bo0tzz test

**Comment by nickrobson** [comment]
Be aware: For sending different message types, Telegram only allows certain file extensions.
(for example, for images only .jpg, .jpeg, .gif, .png, .tif, .bmp are allowed)

This means the "fileName" parameter (which is the second argument for InputFile when taking an InputStream) **needs** to end in one of the allowed file extensions (otherwise it'll return an error).

Unfortunately, this can only be done in the actual send message, as the file extensions change according to where you're trying to send the file - is it a photo? audio? video? voice? By then, it has the same effect as returning the TG error (or an exception when that is implemented.)

**Pull request merged**
